services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    image: othmanelhadrati/frontendapp:v1.1

    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      
    image: othmanelhadrati/backendapp:v1.1

    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./database/medicaloffice.db
